### PR TITLE
Add AlignmentMatrixControl 

### PR DESCRIPTION
**Pull request by saramarcondes**
### Testing instructions

Ensure the [storybook example for G2](https://g2-git-add-alignment-matrix-control.itsjonq.vercel.app/iframe.html?id=components-alignmentmatrixcontrol--default) matches the [Gutenberg storybook example](https://wordpress.github.io/gutenberg/iframe.html?id=components-alignmentmatrixcontrol--default&viewMode=story).

Things that do not work:

* Arrow key navigation
* Tabbing in and out of the component
* IDs are randomly generated and break the snapshot tests every time they run as a new one is generated each time

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@saramarcondes Hai! Following up on this one :). Is it roughly ready for review yet? <3

**Comment by saramarcondes** [comment]
@ItsJonQ It's not! If you don't mind taking a look and seeing if you can prod at the problems that would be super helpful. I'm totally stuck on this one.

**Comment by ItsJonQ** [comment]
>  If you don't mind taking a look and seeing if you can prod at the problems that would be super helpful.

You got it! ❤️

**Comment by ItsJonQ** [comment]
Screen Shot 2020-11-12 at 12 15 39 PM

Looking into this now. I'm attempting to render just the raw Reakit Composite to see if I can get it working.
I can't seem to get the 9x9 up/down movements working. I can only move left and right.

> Tabbing in and out of the component

I think the Tabbing issues are caused by the `Tooltip` trigger (being focusable?)

**Comment by ItsJonQ** [comment]
@saramarcondes Haiii! I just pushed the updates! Lemme know if these changes make sense 🙏

**Comment by saramarcondes** [comment]
@ItsJonQ Oh gosh, missing `...composite` is so obvious now! Thanks for catching that and for the other changes. It all makes sense to me if it does to you!

**Comment by ItsJonQ** [comment]
> Oh gosh, missing ...composite is so obvious now
@saramarcondes I've done this plenty of times.. PLENTY 😂 .

Will do a final check and merge it up.

Thank you for working on this one + review!!! ❤️

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Thanks @saramarcondes !!!

**Pull request merged**
